steps:
# Build a docker image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'gcr.io/steam-potential-343206/myapp', '.' ]
# Push the docker image to container registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ["push", "gcr.io/steam-potential-343206/myapp"]
   # deploy container image to GKE
 - name: 'gcr.io/cloud-builders/kubectl'
   id: Deploy
   args:
   - 'apply'
   - '-f'
   - 'kubernetes.yaml'
   env:
   - 'CLOUDSDK_COMPUTE_REGION=asia-south1-c'
   - 'CLOUDSDK_CONTAINER_CLUSTER=cluster'
