steps:
# Build a docker image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'asia.gcr.io/steam-potential-343206/myapp', '.' ]
# Push the docker image to container registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ["push", "asia.gcr.io/steam-potential-343206/myapp"]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes.yaml/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster'
